default_language_version:
  python: python3.10

exclude: ^sagemaker/.*$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
      args: [--allow-multiple-documents, '--unsafe']
    - id: check-json
    - id: pretty-format-json
      args: [--autofix]
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
      verbose: true
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
    - id: ruff
      args: ["--fix", "--show-source"]
-   repo: https://github.com/rhysd/actionlint
    rev: v1.6.25
    hooks:
      - id: actionlint-system
