cd $JUPYTER_SERVER_ROOT

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE="/home/ec2-user/.local/bin/micromamba";
export MAMBA_ROOT_PREFIX="/home/ec2-user/micromamba";
__mamba_setup="$('/home/ec2-user/.local/bin/micromamba' shell hook --shell bash --prefix '/home/ec2-user/micromamba' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    if [ -f "/home/ec2-user/micromamba/etc/profile.d/micromamba.sh" ]; then
        . "/home/ec2-user/micromamba/etc/profile.d/micromamba.sh"
    else
        export  PATH="/home/ec2-user/micromamba/bin:$PATH"  # extra space after export prevents interference from conda init
    fi
fi
unset __mamba_setup
# <<< mamba initialize <<<
