name: Code Quality
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  dependencies:
    name: Poetry
    uses: ./.github/workflows/poetry.yml
    with:
      image_name: smgrealestate/python-cdk:python-3.10
      home: /home/python
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
